name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::488081132204:role/analistadev-pro"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "analistadev-pro-sa-east-1-terraform-files"
      aws-lock-dynamodb-table: "analistadev-pro-sa-east-1-terraform-lock"